flush ruleset

table inet bynull_filter {
  chain input {
    type filter hook input priority 0; policy drop;
    ct state invalid drop
    ct state established,related accept
    iifname "lo" accept
    tcp dport { 22, 443, 6380 } accept
    ip protocol icmp accept
    ip6 nexthdr icmpv6 accept
  }

  chain forward {
    type filter hook forward priority 0; policy drop;
    ct state invalid drop
    ct state established,related accept
    iifname "docker0" accept
    iifname "br-*" accept
    oifname "docker0" accept
    oifname "br-*" accept
  }

  chain output {
    type filter hook output priority 0; policy accept;
  }
}
