http:
  routers:
    registry:
      entryPoints:
        - websecure
      rule: Host(`registry.dev.nokey.sh`)
      service: registry
      tls:
        certResolver: letsencrypt
    sccache:
      entryPoints:
        - websecure
      rule: Host(`sccache.dev.nokey.sh`)
      service: sccache
      tls:
        certResolver: letsencrypt
    github-webhooks:
      entryPoints:
        - websecure
      rule: Host(`webhooks.dev.nokey.sh`) && Path(`/webhooks/github`) && Method(`POST`)
      service: github-webhooks
      tls:
        certResolver: letsencrypt
    jetstream-events:
      entryPoints:
        - websecure
      rule: Host(`events.dev.nokey.sh`)
      service: jetstream-events
      tls:
        certResolver: letsencrypt

  services:
    registry:
      loadBalancer:
        servers:
          - url: http://10.96.90.10:5000
    sccache:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://127.0.0.1:8333
    github-webhooks:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://10.96.90.20:12000
    jetstream-events:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://10.96.90.30:9222
