http:
  routers:
    registry:
      entryPoints:
        - websecure
      rule: Host(`registry.dev.nokey.sh`)
      service: registry
      tls:
        certResolver: letsencrypt
    sccache:
      entryPoints:
        - websecure
      rule: Host(`sccache.dev.nokey.sh`)
      service: sccache
      tls:
        certResolver: letsencrypt

  services:
    registry:
      loadBalancer:
        servers:
          - url: http://10.96.90.10:5000
    sccache:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://127.0.0.1:8333
