export const authenticationFactAttributeFilter = [
  "action",
  "alt",
  "aria-disabled",
  "aria-hidden",
  "aria-label",
  "aria-labelledby",
  "autocomplete",
  "class",
  "data-nook-passkey-control",
  "disabled",
  "form",
  "formaction",
  "hidden",
  "href",
  "id",
  "name",
  "role",
  "style",
  "title",
  "type",
  "value",
] as const;
