export const authenticationFactAttributeFilter = [
  "action",
  "alt",
  "aria-disabled",
  "aria-hidden",
  "aria-label",
  "aria-labelledby",
  "autocomplete",
  "class",
  "data-nook-manual-checkpoint",
  "data-nook-passkey-control",
  "data-qa",
  "data-testid",
  "disabled",
  "for",
  "form",
  "formaction",
  "hidden",
  "href",
  "id",
  "inert",
  "name",
  "onchange",
  "oninput",
  "placeholder",
  "readonly",
  "role",
  "src",
  "style",
  "title",
  "type",
  "value",
] as const;

export const authenticationFactObserverOptions = {
  attributes: true,
  attributeFilter: [...authenticationFactAttributeFilter],
  childList: true,
  characterData: true,
  subtree: true,
} as const satisfies MutationObserverInit;
