apiVersion: v1
kind: Namespace
metadata:
  name: argo-events
  labels:
    nook.nokey.sh/role: webhook-events
---
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argo-events
spec:
  jetstream:
    version: 2.10.29
    replicas: 3
    streamConfig: |
      maxMsgs: 1000
      maxAge: 1h
      maxBytes: 64MB
      replicas: 3
      duplicates: 300s
      retention: 0
      discard: 0
    settings: |
      max_memory_store: 128MB
      max_file_store: 256MB
    containerTemplate:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 256Mi
    reloaderContainerTemplate:
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 100m
          memory: 64Mi
    metricsContainerTemplate:
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 100m
          memory: 64Mi
