apiVersion: v1
kind: Namespace
metadata:
  name: argo-events
  labels:
    nook.nokey.sh/role: webhook-events
---
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argo-events
spec:
  jetstreamExotic:
    url: nats://eventbus-default-js-svc.argo-events.svc:4222
    accessSecret:
      name: jetstream-argo-client
      key: auth
    streamConfig: |
      maxMsgs: 1000
      maxAge: 24h
      maxBytes: 64MB
      replicas: 3
      duplicates: 300s
      retention: 0
      discard: 0
    tls:
      caCertSecret:
        name: jetstream-server
        key: ca-cert
