export const MAX_MODULE_DELIVERY_STRING_LIST_ENTRIES = 128;
export const MAX_MODULE_DELIVERY_STRING_CODE_UNITS = 4096;
export const MAX_MODULE_DELIVERY_ARTIFACT_IDENTITY_CODE_UNITS = 256;
export const MAX_MODULE_DELIVERY_EVIDENCE_ENTRIES =
  MAX_MODULE_DELIVERY_STRING_LIST_ENTRIES;
export const MAX_MODULE_DELIVERY_EVIDENCE_ENTRY_CODE_UNITS =
  MAX_MODULE_DELIVERY_STRING_CODE_UNITS;
export const MAX_MODULE_DELIVERY_EVIDENCE_CLAIMS =
  MAX_MODULE_DELIVERY_STRING_LIST_ENTRIES;
export const MAX_MODULE_DELIVERY_ACCEPTANCE_REQUIREMENTS =
  MAX_MODULE_DELIVERY_STRING_LIST_ENTRIES;
export const MAX_EXPANDED_PROVIDER_EVIDENCE_IDENTITIES = 128;
export const MAX_MODULE_DELIVERY_EVIDENCE_HANDOFF_BYTES = 262_144;
export const MAX_MODULE_DELIVERY_EVIDENCE_OBJECT_KEYS = 64;
export const MAX_MODULE_DELIVERY_EVIDENCE_ARRAY_ENTRIES =
  MAX_MODULE_DELIVERY_STRING_LIST_ENTRIES;
export const MAX_MODULE_DELIVERY_EVIDENCE_STRING_CODE_UNITS =
  MAX_MODULE_DELIVERY_STRING_CODE_UNITS;
export const MAX_MODULE_DELIVERY_EVIDENCE_DEPTH = 64;
export const MAX_MODULE_DELIVERY_EVIDENCE_IDENTITIES =
  MAX_EXPANDED_PROVIDER_EVIDENCE_IDENTITIES;

/** Raw module-plan transport bounds applied before boundary conversion. */
export const MAX_MODULE_DELIVERY_PLAN_HANDOFF_BYTES = 262_144;
export const MAX_MODULE_DELIVERY_PLAN_DEPTH = 64;
export const MAX_MODULE_DELIVERY_PLAN_OBJECT_KEYS = 64;
/** Keep this above the existing 4032 edge-contract collection cap. */
export const MAX_MODULE_DELIVERY_PLAN_ARRAY_ENTRIES = 4_096;
export const MAX_MODULE_DELIVERY_PLAN_AGGREGATE_NODES = 32_768;
export const MAX_MODULE_DELIVERY_PLAN_AGGREGATE_STRING_CODE_UNITS = 131_072;
