export const EXECUTABLE_SKILL_REGISTRY_INSPECTION_TIMEOUT_MS = 180_000;
export const EXECUTABLE_SKILL_PROVISIONING_TIMEOUT_MS = 180_000;
export const EXECUTABLE_SKILL_TEARDOWN_ATTEMPT_TIMEOUT_MS = 3_000;
export const EXECUTABLE_SKILL_TEARDOWN_ATTEMPT_COUNT = 2;
export const EXECUTABLE_SKILL_WORKFLOW_ORCHESTRATION_MARGIN_MS = 10_000;

export function executableSkillWorkflowMinimumTimeoutMs(
  maximumRegisteredExecutionTimeoutMs: number,
): number {
  const confirmedTeardownTimeoutMs =
    EXECUTABLE_SKILL_TEARDOWN_ATTEMPT_TIMEOUT_MS *
    EXECUTABLE_SKILL_TEARDOWN_ATTEMPT_COUNT;
  return (
    EXECUTABLE_SKILL_REGISTRY_INSPECTION_TIMEOUT_MS +
    EXECUTABLE_SKILL_PROVISIONING_TIMEOUT_MS +
    maximumRegisteredExecutionTimeoutMs +
    confirmedTeardownTimeoutMs +
    EXECUTABLE_SKILL_WORKFLOW_ORCHESTRATION_MARGIN_MS
  );
}
