apiVersion: v1
kind: Service
metadata:
  name: nook-buildkit-proof-0
  namespace: arc-runners
spec:
  selector:
    statefulset.kubernetes.io/pod-name: nook-buildkit-0
  ports:
    - name: buildkit
      port: 1234
      targetPort: buildkit
---
apiVersion: v1
kind: Service
metadata:
  name: nook-buildkit-proof-1
  namespace: arc-runners
spec:
  selector:
    statefulset.kubernetes.io/pod-name: nook-buildkit-1
  ports:
    - name: buildkit
      port: 1234
      targetPort: buildkit
---
apiVersion: v1
kind: Service
metadata:
  name: nook-buildkit-proof-2
  namespace: arc-runners
spec:
  selector:
    statefulset.kubernetes.io/pod-name: nook-buildkit-2
  ports:
    - name: buildkit
      port: 1234
      targetPort: buildkit
