apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: nook-hive
spec:
  api:
    address: 10.201.0.1
    sans:
      - 127.0.0.1
      - localhost
      - 10.201.0.1
    extraArgs:
      encryption-provider-config: /var/lib/k0s/pki/hive-encryption-provider.yaml
  controllerManager:
    extraArgs:
      terminated-pod-gc-threshold: "200"
  network:
    provider: kuberouter
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
    kuberouter:
      ipMasq: true
  storage:
    type: etcd
  telemetry:
    enabled: false
