/** Browser-runtime message identifiers emitted into the extension manifest. */
export const BROWSER_MESSAGE_KEYS = {
  PasskeySaveTitle: 'passkeySaveTitle',
  PasskeyUseBrowser: 'passkeyUseBrowser',
  PasskeyUseTitle: 'passkeyUseTitle',
  WidgetAuthenticatorFillFailed: 'widgetAuthenticatorFillFailed',
  WidgetAuthenticatorFilled: 'widgetAuthenticatorFilled',
  WidgetAuthenticatorPickerCanceled: 'widgetAuthenticatorPickerCanceled',
  WidgetAuthenticatorPickerOpened: 'widgetAuthenticatorPickerOpened',
  WidgetAuthenticatorUnlock: 'widgetAuthenticatorUnlock',
  WidgetAuthenticatorWorking: 'widgetAuthenticatorWorking',
  WidgetBackupCancel: 'widgetBackupCancel',
  WidgetBackupChooseAuthenticator: 'widgetBackupChooseAuthenticator',
  WidgetBackupEmpty: 'widgetBackupEmpty',
  WidgetBackupFailed: 'widgetBackupFailed',
  WidgetBackupPaste: 'widgetBackupPaste',
  WidgetBackupReview: 'widgetBackupReview',
  WidgetBackupSaved: 'widgetBackupSaved',
  WidgetBackupTitle: 'widgetBackupTitle',
  WidgetBackupWorking: 'widgetBackupWorking',
  WidgetCollapse: 'widgetCollapse',
  WidgetConnectVault: 'widgetConnectVault',
  WidgetDismiss: 'widgetDismiss',
  WidgetEnrollAmbiguous: 'widgetEnrollAmbiguous',
  WidgetEnrollFailed: 'widgetEnrollFailed',
  WidgetEnrollNoQr: 'widgetEnrollNoQr',
  WidgetEnrollPreview: 'widgetEnrollPreview',
  WidgetEnrollSaved: 'widgetEnrollSaved',
  WidgetEnrollStaging: 'widgetEnrollStaging',
  WidgetEnrollTitle: 'widgetEnrollTitle',
  WidgetEnrollUnlock: 'widgetEnrollUnlock',
  WidgetEnrollUnsupported: 'widgetEnrollUnsupported',
  WidgetEnrollVerifyPending: 'widgetEnrollVerifyPending',
  WidgetEnrollWorking: 'widgetEnrollWorking',
  WidgetExpand: 'widgetExpand',
  WidgetFillFailed: 'widgetFillFailed',
  WidgetFilledManual: 'widgetFilledManual',
  WidgetGeneratePasswordFailed: 'widgetGeneratePasswordFailed',
  WidgetGeneratePasswordWorking: 'widgetGeneratePasswordWorking',
  WidgetGeneratedPasswordFilled: 'widgetGeneratedPasswordFilled',
  WidgetLoginPickerCanceled: 'widgetLoginPickerCanceled',
  WidgetLoginPickerOpened: 'widgetLoginPickerOpened',
  WidgetNoMatch: 'widgetNoMatch',
  WidgetOpenVault: 'widgetOpenVault',
  WidgetPasskeyCeremonyStarted: 'widgetPasskeyCeremonyStarted',
  WidgetPasskeyControlMissing: 'widgetPasskeyControlMissing',
  WidgetPilotLabel: 'widgetPilotLabel',
  WidgetSaveLoginFailed: 'widgetSaveLoginFailed',
  WidgetSaveLoginNotNow: 'widgetSaveLoginNotNow',
  WidgetSaveLoginSavedDescription: 'widgetSaveLoginSavedDescription',
  WidgetSaveLoginSavedTitle: 'widgetSaveLoginSavedTitle',
  WidgetSavedAuthenticator: 'widgetSavedAuthenticator',
  WidgetSubmitted: 'widgetSubmitted',
  WidgetTakeOver: 'widgetTakeOver',
  WidgetUnlockThenContinue: 'widgetUnlockThenContinue',
  WidgetVaultConnected: 'widgetVaultConnected',
  WidgetVaultNotConnected: 'widgetVaultNotConnected',
  WidgetWorking: 'widgetWorking',
} as const

export type BrowserMessageKey =
  (typeof BROWSER_MESSAGE_KEYS)[keyof typeof BROWSER_MESSAGE_KEYS]
