import type {
  NookJoinRequest,
  NookSecretRecord,
  NookVaultManager,
  NookVaultMember,
  NookVaultSyncResult,
} from './nook-wasm/nook_wasm'
import {
  default as initNookWasm,
  NookVaultManager as NookVaultManagerClass,
  NookSecretFormFields,
  buildSecretYaml as wasmBuildSecretYaml,
  generateId as wasmGenerateId,
  generatePassword as wasmGeneratePassword,
  generateSecretId as wasmGenerateSecretId,
} from './nook-wasm/nook_wasm'
import { createLogger, initWasmLogging } from '$lib/log'

await initNookWasm()
initWasmLogging()

export type {
  NookJoinRequest,
  NookSecretRecord,
  NookVaultManager,
  NookVaultMember,
  NookVaultSyncResult,
  NookSecretFormFields,
}

/** UI alias — same typed object exported from WASM. */
export type JoinRequest = NookJoinRequest
export type VaultMember = NookVaultMember

/** UI-only tag for the add-secret type picker — canonical schema lives in `nook-core`. */
export type VaultItemType = 'login' | 'api-key' | 'seed-phrase' | 'secure-note'

/** Compact random id generated by `nook-core`. */
export function generateId(): string {
  return wasmGenerateId()
}

/** Prefixed secret-store item id generated by `nook-core`. */
export function generateSecretId(): string {
  return wasmGenerateSecretId()
}

/** Cryptographically secure password — does not borrow the vault manager. */
export function generatePassword(
  length: number,
  lowercase: boolean,
  uppercase: boolean,
  numbers: boolean,
  symbols: boolean,
): string {
  return wasmGeneratePassword(length, lowercase, uppercase, numbers, symbols)
}

export function isoTimestamp(): string {
  return new Date().toISOString()
}

export type VaultSyncAccessStatus =
  | 'ready'
  | 'new_vault'
  | 'needs_enrollment'
  | 'join_pending'
  | 'password_required'

export async function getVaultManager(): Promise<NookVaultManager> {
  const loadWasm = async () => {
    await initNookWasm()
    initWasmLogging()
    const manager = new NookVaultManagerClass()
    drainWasmStatusIntoLog(manager)
    return manager
  }

  const timeout = new Promise<never>((_, reject) => {
    setTimeout(
      () =>
        reject(
          new Error(
            'Vault engine timed out while loading. Refresh and try again.',
          ),
        ),
      15_000,
    )
  })

  return Promise.race([loadWasm(), timeout])
}

const wasmLog = createLogger('wasm')

/**
 * Pipe the wasm manager's status channel (e.g. `GITHUB_FETCH_START`,
 * `DECRYPT_SUCCESS`) into the persistent IndexedDB log at debug level.
 *
 * Uses the non-blocking `drainStatusLog` on an interval — the awaiting
 * `next_status` variant would hold the wasm-bindgen borrow and deadlock
 * every `&mut self` manager call.
 */
function drainWasmStatusIntoLog(manager: NookVaultManager) {
  setInterval(() => {
    try {
      for (const status of manager.drainStatusLog()) {
        wasmLog.debug(status)
      }
    } catch {
      // Manager may be mid-borrow by an async &mut call; retry next tick.
    }
  }, 500)
}

/** Build a validated YAML payload for `add_secret` / `replace_secret`. */
export function buildSecretYaml(
  secretType: VaultItemType,
  fields: Record<string, string>,
): string {
  return wasmBuildSecretYaml(
    secretType,
    new NookSecretFormFields(
      fields.websiteUrl ?? null,
      fields.username ?? null,
      fields.password ?? null,
      fields.notes ?? null,
      fields.key ?? null,
      fields.expiresAt ?? null,
      fields.name ?? null,
      fields.seed ?? null,
      fields.title ?? null,
      fields.note ?? null,
    ),
  )
}
