apiVersion: v1
kind: Namespace
metadata:
  name: hive-system
  labels:
    hive.nook.sh/role: workers
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: hive-data
  labels:
    hive.nook.sh/role: data
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
